# Generated by Django 5.2.17 on 2026-08-30 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=42, unique=True, validators=[django.core.validators.RegexValidator(message='Must be a 0x-prefixed 40-character hex address.', regex='^0x[a-fA-F0-9]{40}$')])),
                ('total_volume', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('tx_count', models.PositiveIntegerField(default=0)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('last_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_tx_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
